### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by Yurriki** [gorkaydemir/ADAPT#1]
First of all, congratulations on your paper being accepted by ICCV2023. Your paper is really helpful for my study, but due to hardware limitations, I only have two RTX 3090 graphics cards and 64GB of memory. Is this hardware configuration sufficient? Can you publish the hardware conditions of your experiment and the approximate time required for data preprocessing and model training?

**Comment by gorkaydemir** [comment]
Hi,
Thank you for your interest in the paper. 
It takes ~2 hours to extract ex_list, ~20 minutes to extract eval.ex_list and ~50 minutes to extend ex_list to extended_ex_list. I am planning to share these preprocessed data files soon to facilitate handling of preprocessing steps.

I used 4 Tesla T4 GPUs and 200GB of RAM for training. Each epoch takes ~3 hours, with an additional ~15 minutes for evaluation on validation data. A large amount of RAM is necessary because the training process involves loading data entirely into a Dataset instance. I attempted to enhance this by loading data incrementally from storage at each iteration, but it unfortunately resulted in extended training times.

Best

**Comment by Yurriki** [comment]
Thanks, my problem is solved.

**Comment by penglo** [comment]
> First of all, congratulations on your paper being accepted by ICCV2023. Your paper is really helpful for my study, but due to hardware limitations, I only have two RTX 3090 graphics cards and 64GB of memory. Is this hardware configuration sufficient? Can you publish the hardware conditions of your experiment and the approximate time required for data preprocessing and model training?

"Hello, sorry to disturb you. It seems that you have studied the ADAPT paper. I have a question and would like to ask for your advice. Is it convenient to communicate directly? My email is lipl23@mails.jlu.edu.cn
